### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by dwhitney** [Thimoteus/purescript-promises#2]
Not sure where else to submit a thank you, but literally yesterday I was thinking to myself "why isn't `Promise` a monad in `purescript-aff-promise`." I nearly did all of this work in a PR. Much gratitude!

**Comment by Thimoteus** [comment]
No problem, I was sitting in an airport with a 15 hour layover and thought I might be able to hack something usable to pass the time. Glad you find it useful!
